spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/blog_engine?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Europe/Moscow
spring.datasource.username: root
spring.datasource.password: rootroot
spring.jpa.hibernate.ddl-auto: none

spring.jpa.show-sql: true

engine.title: DevPub
engine.subtitle: Рассказы разработчиков
engine.phone: +7 903 687-35-84
engine.email: warlordkolomna@bk.ru
engine.copyright: Олег Овечников
engine.copyrightFrom: 2021
