server:
  port: ${PORT:8080}

spring:

  servlet:
    multipart:
      max-file-size: 5MB

  messages:
    basename: lang.messages

  datasource:
    url: jdbc:${JAWSDB_URL:mysql://localhost:3306/blog_engine?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Europe/Moscow}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootroot

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:username}
    password: ${MAIL_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          enable: true
          starttls:
            enable: true

engine:
  title: DevPub
  subtitle: Разговорчики разработчиков
  phone: +7 903 687-35-84
  email: warlordkolomna@bk.ru
  copyright: Олег Овечников
  copyrightFrom: 2021

captcha:
  termOf: 60