-- liquibase formatted sql
-- changeset Death:init-data

insert into global_settings(code, name, value) values ('MULTIUSER_MODE', 'Многопользовательский режим', 'NO');
insert into global_settings(code, name, value) values ('POST_PREMODERATION', 'Премодерация постов', 'NO');
insert into global_settings(code, name, value) values ('STATISTICS_IS_PUBLIC', 'Показывать всем статистику блога', 'YES');

insert into users (is_moderator, reg_time, name, email, password, code, photo) values (1, '2005-03-29 03:39:45', 'Harmonia Truwert', 'htruwert0@simplemachines.org', 'ewBTmX2M6u1WreL', 'WeY8G', 'http://bloglines.com/nisl/nunc.aspx');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (1, '2008-01-09 10:26:56', 'Normie Penk', 'npenk1@blogger.com', 'XNTS9i4mCcU05vj', 'aYPQf', 'http://yellowbook.com/ut/erat/curabitur/gravida/nisi/at/nibh.jpg');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (1, '2010-07-06 03:44:41', 'Eolande Wiz', 'ewiz2@rambler.ru', 'PuIblgip78nx6jQ', 'JhGSA', 'https://census.gov/faucibus/accumsan/odio.js');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (1, '2001-03-13 05:49:42', 'Meggy Ianni', 'mianni3@hostgator.com', 'obdLG2A5HrpBsMU', 'Qyewl', 'https://plala.or.jp/ac/diam/cras/pellentesque/volutpat/dui/maecenas.jpg');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (1, '2006-11-25 23:18:12', 'Ingamar Driffield', 'idriffield4@ehow.com', 'K1ChAz4AaPnr8D3', '72fwy', 'http://ehow.com/porttitor/lacus.jpg');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (1, '2011-06-13 08:47:52', 'Cody Onele', 'conele5@wikia.com', '2hfdTZNvsM8srPm', 'X6ZHp', 'https://addthis.com/placerat/praesent/blandit/nam.jpg');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (1, '2010-10-15 02:32:46', 'Lacey Ellwood', 'lellwood6@e-recht24.de', 'yTx6o1fU9U58Vhi', 'fBX27', 'https://cnet.com/mauris/vulputate/elementum/nullam/varius.json');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (1, '2007-01-04 10:22:20', 'Felike Daysh', 'fdaysh7@earthlink.net', 'rW0ntZgRgcbCGYz', '83qeR', 'https://wikipedia.org/ultrices/vel/augue/vestibulum/ante/ipsum/primis.aspx');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (1, '2000-06-02 20:46:08', 'Wynn Wolfenden', 'wwolfenden8@blogspot.com', 'Z0SNwSZwQQcvU4I', 'IeOMw', 'https://com.com/libero/non/mattis/pulvinar/nulla/pede/ullamcorper.aspx');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (1, '2016-04-28 06:31:24', 'Trude Cromblehome', 'tcromblehome9@senate.gov', 'DeHtDW4fUeHnOvF', 'VTaE3', 'https://godaddy.com/non/mauris/morbi/non/lectus/aliquam.xml');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2011-05-23 23:35:48', 'Marthe Dinsdale', 'mdinsdalea@chron.com', 'xnLHle7Z5ne16sp', 'fgeFG', 'https://theatlantic.com/tristique/in/tempus/sit.json');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2003-01-06 14:57:37', 'Stormi Sands-Allan', 'ssandsallanb@marketwatch.com', 'm1QHxmhL3pinucN', 'alVKp', 'https://si.edu/luctus/rutrum/nulla/tellus/in/sagittis.aspx');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2014-08-02 10:38:00', 'Aveline Sayton', 'asaytonc@moonfruit.com', 'WtVuusP0IQXUGUx', 'lJOuc', 'https://phpbb.com/lacinia.html');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2001-07-12 04:00:16', 'Cam Klass', 'cklassd@ft.com', 'Y6BxpMaDPzfSEeI', 'bENPA', 'https://lulu.com/maecenas/ut/massa/quis/augue/luctus.aspx');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2018-07-11 11:01:21', 'Reggie Jecock', 'rjecocke@istockphoto.com', 'bnmmrs62PkvTbJy', 'TF6aq', 'https://cisco.com/consequat/ut/nulla/sed/accumsan/felis.html');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2004-09-21 05:13:31', 'Howie Kilbourne', 'hkilbournef@vkontakte.ru', 'tDdpwyKRY158hXL', 'trMiD', 'https://youtube.com/mauris/sit/amet.aspx');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2000-12-21 06:45:12', 'Cybil Franzettoini', 'cfranzettoinig@netlog.com', '47IFFrH5vsnVkyk', 'C2DK3', 'http://amazon.co.uk/nisl/venenatis/lacinia/aenean.jsp');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2004-05-10 04:23:07', 'Cari Juanico', 'cjuanicoh@youtube.com', 'X8oWUHNTsZhUgWb', 'Ui9Yr', 'http://wordpress.com/est/quam/pharetra/magna/ac/consequat/metus.xml');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2005-05-19 05:29:42', 'Brigham Pyburn', 'bpyburni@sphinn.com', 'm5656xudG6T9AdB', 'HuQcZ', 'http://redcross.org/donec/pharetra/magna/vestibulum/aliquet/ultrices/erat.html');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2015-12-29 00:17:03', 'Biddy Sheard', 'bsheardj@umich.edu', 'oA0FmK230H9Cqcn', 'CEJSs', 'https://clickbank.net/tincidunt/in/leo/maecenas.js');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2012-10-29 02:43:54', 'Blayne Oxer', 'boxerk@livejournal.com', 'qo0WcG0W5PIPPT7', 'uRvZY', 'https://cbc.ca/velit/nec/nisi/vulputate.xml');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2005-09-21 15:51:02', 'Gwenette Lanston', 'glanstonl@facebook.com', '14Jpr7LZAjHJjpC', 'Im5FG', 'https://ebay.com/nulla/eget.js');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2007-12-27 04:46:39', 'Jilli Weatherall', 'jweatherallm@tiny.cc', 'Q97slDwFJJnvR2Z', 'Q3HeX', 'https://instagram.com/augue/quam/sollicitudin/vitae/consectetuer/eget.xml');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2005-10-21 16:06:36', 'Henriette Tuckwell', 'htuckwelln@yellowbook.com', '8LdgEVaMKbyQFQg', 'Q3zvB', 'http://lulu.com/morbi/a/ipsum/integer.aspx');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2007-11-10 03:04:55', 'Nev Thurstan', 'nthurstano@slate.com', 'yObqJJYWMsas4cn', 'ms5Rv', 'http://sbwire.com/vulputate/vitae/nisl/aenean/lectus/pellentesque.js');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2006-07-27 18:48:48', 'Terrence Muskett', 'tmuskettp@businesswire.com', 'H67wwjlDHAdyxCR', 'Bzm3Y', 'http://telegraph.co.uk/iaculis/congue/vivamus/metus/arcu/adipiscing/molestie.png');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2008-07-13 15:58:45', 'Herc Bulbrook', 'hbulbrookq@dmoz.org', 'rKiLNNxzSsE6xiL', 'bzWbO', 'https://wikia.com/ornare/imperdiet/sapien/urna/pretium/nisl.png');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2019-07-20 08:44:14', 'Bev Harrower', 'bharrowerr@globo.com', 'u96ufQq8iHgmNov', 'y5Xua', 'https://accuweather.com/lectus/vestibulum/quam/sapien.js');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2009-11-01 00:03:24', 'Tresa Sweetland', 'tsweetlands@domainmarket.com', 'CNz8dFIx2mT8yI5', 'wEKlf', 'https://tamu.edu/in/quis/justo/maecenas/rhoncus.jsp');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2003-02-24 01:52:14', 'Valene Leech', 'vleecht@pbs.org', 'UX3zobdgTmCmL3I', 'dRYX5', 'http://scientificamerican.com/elit.json');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2000-10-31 15:01:06', 'Lynnelle Stoller', 'lstolleru@globo.com', 'yhKc2Rv7cnXsaD3', 'yey3I', 'http://fastcompany.com/morbi/sem.jsp');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2015-11-18 23:51:49', 'Anallise Querree', 'aquerreev@naver.com', '1lI0Xbygu62C1tD', 'UdaUH', 'http://sphinn.com/lacus/purus/aliquet/at/feugiat.js');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2012-01-14 09:49:05', 'Dyane Lobe', 'dlobew@github.com', 'BexRZpX70xsCtnt', 'qD2DP', 'https://bloglovin.com/id.png');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2007-09-25 16:53:54', 'Dom Noddings', 'dnoddingsx@intel.com', 'ngHzgVT3P1ZL9rm', 'CwwsI', 'https://yandex.ru/massa/tempor/convallis/nulla/neque/libero/convallis.png');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2016-12-21 19:03:50', 'Chadwick Eastham', 'ceasthamy@acquirethisname.com', 'NhUIFSIXSPwk31d', 'Whcv0', 'http://123-reg.co.uk/eu.html');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2019-12-09 12:14:06', 'Norene Buttner', 'nbuttnerz@devhub.com', 'FVPlMf7QPPNX7js', 'xDbvX', 'https://latimes.com/ipsum/dolor/sit/amet.jsp');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2015-08-06 11:58:32', 'Thornton Romanski', 'tromanski10@ebay.co.uk', 'yVx9UU95az0bHpT', '6ZuzZ', 'https://scribd.com/sed/vestibulum/sit/amet/cursus.jpg');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2006-09-07 03:18:10', 'Jean McGurk', 'jmcgurk11@lulu.com', 'ZIkCmh6JPiNEkCB', '5m5gD', 'https://ft.com/pede/morbi/porttitor.png');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2009-10-31 04:52:45', 'Pansie MacAdie', 'pmacadie12@virginia.edu', 'pKWU3KOpHbBUmuN', 'tgbxy', 'http://domainmarket.com/tempus/vivamus/in.xml');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2019-01-17 02:22:34', 'Gerek Kem', 'gkem13@ehow.com', 'S7CUzoR8TZjtPc7', 'KPc8N', 'https://jigsy.com/nibh/fusce/lacus/purus.html');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2006-01-24 12:20:02', 'Bathsheba Blasio', 'bblasio14@hp.com', 'MSWbE34yyXN1Vwg', 'FsGZ2', 'https://state.gov/id/massa/id.jsp');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2014-02-10 22:04:36', 'Arabella Jowle', 'ajowle15@themeforest.net', 'XGHNAV6MnxrgN0w', 'LQ1z7', 'http://ocn.ne.jp/sem/praesent.json');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2018-10-18 05:28:43', 'Gerhardine Craig', 'gcraig16@mozilla.com', 'kfi3kfpMnx0YZ6f', 'E8G8a', 'http://dropbox.com/pede/morbi/porttitor/lorem/id.json');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2014-09-06 03:52:48', 'Caryl Navan', 'cnavan17@oaic.gov.au', 'hgMMGzbspqZj00o', 'jhS2s', 'https://state.tx.us/consectetuer/eget.aspx');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2006-03-24 23:56:49', 'Thebault Jentzsch', 'tjentzsch18@forbes.com', 'fF0W1tU3xQmqRNl', 'gtzFl', 'https://technorati.com/turpis/integer/aliquet.json');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2001-08-10 23:51:37', 'Avis Dinsey', 'adinsey19@trellian.com', 'fxGuIpriXjqecx2', 'Uv2sS', 'http://unc.edu/in/sagittis/dui/vel/nisl/duis.json');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2011-05-25 21:26:47', 'Erik Buckam', 'ebuckam1a@printfriendly.com', '1SapZ1sdwAgVmMe', 'nwNKD', 'http://yandex.ru/sem.aspx');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2012-05-04 14:50:57', 'Joby Pickless', 'jpickless1b@smh.com.au', 'moHhI55QH0B4vrZ', '2T4h8', 'https://psu.edu/orci/eget/orci/vehicula/condimentum/curabitur.json');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2006-05-04 12:57:49', 'Sheff Christou', 'schristou1c@hao123.com', 'lEOTnrbkhZUcEK2', 'm16Pe', 'https://sitemeter.com/semper/est/quam/pharetra.xml');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2016-11-16 05:52:08', 'Maddi Muzzlewhite', 'mmuzzlewhite1d@ezinearticles.com', 'w2p0irZuTmmaMQZ', 'kheel', 'https://hc360.com/elit/ac/nulla/sed/vel.js');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2009-04-23 03:50:22', 'Merna Neggrini', 'mneggrini1e@deviantart.com', 'cqlq3n6kykQqseG', 'SxTkZ', 'https://shinystat.com/ullamcorper/augue/a/suscipit.aspx');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2003-10-12 17:01:06', 'Simona Horsfield', 'shorsfield1f@ucoz.ru', 'EsgxhBgrpjJRkmO', 'xLcfu', 'https://ebay.com/turpis/adipiscing/lorem/vitae/mattis.jpg');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2015-01-13 14:43:43', 'Cassondra Drysdall', 'cdrysdall1g@nymag.com', 'KpEMTLQBOuutoYR', 'bGqmW', 'https://cornell.edu/duis/at/velit/eu/est/congue.png');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2009-03-24 05:46:33', 'Hewitt Mewhirter', 'hmewhirter1h@wix.com', 'vYMx0LPX5rR1SpY', 'o9P99', 'http://wufoo.com/morbi/a.jsp');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2013-03-13 11:04:51', 'Shaw Cesconi', 'scesconi1i@flavors.me', 'V3LOQztBIeOQWTA', '49sCT', 'https://noaa.gov/curabitur/at.js');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2001-08-12 11:51:34', 'Carlota Tenman', 'ctenman1j@epa.gov', 'RXlX9uHDQKUmeyb', 'CUb6H', 'https://furl.net/venenatis.jsp');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2002-07-27 03:54:47', 'Monroe Welberry', 'mwelberry1k@timesonline.co.uk', 'EXLNFz56cseOs32', 'H4oKx', 'http://noaa.gov/eget/congue/eget/semper/rutrum/nulla.png');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2002-12-29 15:46:29', 'Corene Paoli', 'cpaoli1l@nih.gov', 'fLv24Nlu3QUyIB8', '9EtvG', 'https://delicious.com/tristique/tortor/eu/pede.html');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2006-11-17 12:02:07', 'Velma Cranke', 'vcranke1m@cbsnews.com', 'gUge8RdvqfANAqN', 'X73cw', 'https://freewebs.com/integer.jpg');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2016-12-09 00:24:14', 'Robby Lutman', 'rlutman1n@google.com.br', 'PdnC2QxNwiOuVyU', 'xBcb0', 'https://posterous.com/in/leo/maecenas/pulvinar/lobortis.png');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2005-08-20 21:09:13', 'Casey Standall', 'cstandall1o@mysql.com', 'hRlSeJnZuE753Eg', 'kdpbz', 'http://springer.com/eros/viverra.xml');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2016-01-01 14:42:44', 'Petronia Du Plantier', 'pdu1p@angelfire.com', 'lGUWPrGwoFb3aMs', 'SZ8vG', 'http://1688.com/odio/consequat/varius.png');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2016-12-06 10:19:31', 'Velvet Grindley', 'vgrindley1q@opensource.org', '2bAORoYhfs3Gkzn', 'Pnz8G', 'http://icio.us/vel/est/donec/odio/justo/sollicitudin.jpg');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2009-01-02 21:39:33', 'Correy MacLeese', 'cmacleese1r@dmoz.org', 'GHG0zTucCwgFpWo', 'bdsNz', 'http://state.tx.us/primis.xml');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2004-05-04 16:25:33', 'Loren Domino', 'ldomino1s@wix.com', 'SalO6uWd5qcYyT1', 'CoWji', 'http://mail.ru/vestibulum/sed/magna/at.xml');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2011-05-04 03:29:40', 'Sophia Mowbray', 'smowbray1t@ca.gov', 'UPe9Fsun02t42N9', 'Jfipu', 'http://washingtonpost.com/aliquam/lacus/morbi/quis/tortor/id.js');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2007-07-03 06:46:31', 'Stacey Moulin', 'smoulin1u@seattletimes.com', 'chv9lQBfyu4BGwo', 'sBmeT', 'http://webs.com/suspendisse.json');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2006-03-03 08:20:58', 'Lin Pockey', 'lpockey1v@zimbio.com', 'cp4mmvXuKYn9FMq', 'rR5Hc', 'https://apple.com/amet/sapien.xml');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2001-09-13 13:13:06', 'Faunie Loncaster', 'floncaster1w@oaic.gov.au', 'dOVSMZbrxS2mhXR', 'gJNuC', 'http://fda.gov/felis/fusce.jsp');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2019-07-23 22:26:17', 'Horten Trapp', 'htrapp1x@vinaora.com', 'GszMKc2GKBQANKA', 'NF1ly', 'https://so-net.ne.jp/rhoncus/aliquam.xml');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2011-03-03 18:46:04', 'Kerri Fish', 'kfish1y@mashable.com', 'aede7mhiWUr68E5', 'hhaFn', 'https://epa.gov/interdum/mauris/ullamcorper/purus.jsp');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2004-03-05 18:08:28', 'Carlo Aspden', 'caspden1z@shutterfly.com', 'iXcKudxHF9D52JF', 'G8HnV', 'http://dot.gov/ut/suscipit/a/feugiat/et/eros/vestibulum.jpg');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2015-03-22 19:36:47', 'Timmy Aldhouse', 'taldhouse20@hud.gov', 'pl3bI8PxHfK3qFl', 'h5spR', 'https://netlog.com/mattis/egestas/metus/aenean.html');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2009-10-07 02:05:06', 'Yancey Aleksandrikin', 'yaleksandrikin21@liveinternet.ru', 'fFIu353CvvMFywy', '8wXta', 'https://nationalgeographic.com/cursus/vestibulum.js');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2010-01-25 00:11:07', 'Doug Castard', 'dcastard22@java.com', 'JzyvoT89tTNU7iQ', 'hHFf0', 'http://geocities.com/varius/nulla/facilisi/cras/non.json');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2000-12-30 13:24:38', 'Pippy Standidge', 'pstandidge23@histats.com', 'ItdbadfJAnqPXqP', 'bnARc', 'https://hp.com/nisl/ut.xml');
insert into users (is_moderator, reg_time, name, email, password, code, photo) values (0, '2010-07-05 08:04:32', 'Hetty Polson', 'hpolson24@accuweather.com', 'tdTte0HnWrkUwV8', 'b5fhz', 'https://simplemachines.org/nulla/pede/ullamcorper/augue/a.jsp');

insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 3, 2, 51, '2016-07-04 17:24:51', 'Cras in purus eu magna vulputate luctus.', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 379);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 2, 9, 39, '2009-07-15 02:12:29', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', 546);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 3, 7, 45, '2008-06-17 01:13:30', 'Nulla ut erat id mauris vulputate elementum.', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', 59);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 2, 4, 56, '2014-11-07 13:01:40', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', 548);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 2, 3, 15, '2014-09-20 21:48:29', 'Nullam molestie nibh in lectus.', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 346);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 1, 3, 46, '2014-05-02 15:35:56', 'Sed vel enim sit amet nunc viverra dapibus.', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 586);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 1, 3, 59, '2007-12-06 01:47:08', 'Pellentesque ultrices mattis odio.', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 301);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 3, 8, 18, '2002-08-03 00:13:21', 'Vivamus tortor.', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 193);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 1, 3, 35, '2019-07-25 15:40:39', 'Duis mattis egestas metus.', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 828);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 2, 6, 46, '2010-11-30 13:24:14', 'Morbi vel lectus in quam fringilla rhoncus.', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 409);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 1, 8, 31, '2003-12-10 08:08:26', 'Phasellus <div>id<div> sapien in sapien iaculis congue.', 'Pellentesque <div>ultrices<div> mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 384);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 3, 3, 48, '2007-08-31 06:38:57', 'Nulla tempus.', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 33);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 2, 6, 21, '2010-07-09 03:31:56', 'Nunc rhoncus dui vel sem.', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 21);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 3, 9, 42, '2015-06-23 07:59:33', 'Praesent lectus.', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', 464);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 3, 8, 5, '2012-07-04 18:02:33', 'Vivamus in felis eu sapien cursus vestibulum.', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 68);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 1, 2, 14, '2016-08-26 07:18:44', 'Vivamus vestibulum sagittis sapien.', 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 506);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 1, 5, 59, '2000-12-10 09:59:43', 'Nulla nisl.', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 880);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 1, 2, 46, '2018-08-30 11:06:03', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', 630);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 2, 5, 54, '2013-06-13 12:59:24', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 12);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 1, 8, 20, '2018-04-06 17:57:09', 'Vestibulum sed magna at nunc commodo placerat.', 'Duis bibendum.', 799);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 1, 2, 4, '2003-09-07 23:22:01', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 282);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 3, 5, 39, '2010-02-11 19:03:17', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', 459);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 2, 3, 6, '2014-09-09 12:40:12', 'Cras in purus eu magna vulputate luctus.', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 363);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 2, 4, 44, '2004-11-22 12:33:12', 'Morbi non lectus.', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 220);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 3, 1, 12, '2004-12-01 08:00:09', 'Nam tristique tortor eu pede.', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 648);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 3, 7, 6, '2001-10-19 04:37:21', 'Nam tristique tortor eu pede.', 'Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', 226);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 1, 9, 44, '2008-06-25 09:32:32', 'Nulla justo.', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', 508);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 2, 7, 40, '2003-03-27 23:53:52', 'Praesent lectus.', 'Ut at dolor quis odio consequat varius. Integer ac leo.', 1000);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 3, 10, 30, '2009-12-01 17:08:13', 'Sed sagittis.', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 674);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 3, 3, 29, '2002-09-22 05:45:53', 'Praesent lectus.', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 577);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 3, 7, 16, '2014-08-05 04:50:42', 'In congue.', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 322);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 2, 7, 70, '2007-04-06 18:07:51', 'Ut at dolor quis odio consequat varius.', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 568);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 2, 5, 18, '2009-12-27 19:51:32', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 374);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 1, 4, 8, '2007-05-20 07:10:49', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Maecenas pulvinar lobortis est.', 58);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 2, 1, 27, '2002-11-12 07:09:40', 'Vivamus vel nulla eget eros elementum pellentesque.', 'Suspendisse potenti.', 238);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 1, 9, 77, '2014-12-09 16:15:16', 'Nullam porttitor lacus at turpis.', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 772);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 2, 8, 27, '2000-09-13 22:52:18', 'Duis mattis egestas metus.', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 651);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 2, 8, 32, '2013-03-17 06:06:24', 'Donec dapibus.', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 789);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 1, 6, 16, '2007-08-27 06:30:01', 'Nam tristique tortor eu pede.', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 524);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 1, 6, 33, '2009-01-05 19:16:10', 'Nullam varius.', 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', 244);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 1, 2, 71, '2006-08-31 21:12:23', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 855);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 2, 10, 69, '2012-06-14 09:43:20', 'Curabitur convallis.', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 365);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 1, 7, 46, '2005-03-30 11:02:10', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 825);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 3, 5, 21, '2004-07-12 12:07:38', 'Sed ante.', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 717);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 2, 9, 37, '2012-12-19 07:05:25', 'Proin risus.', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 107);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 3, 1, 68, '2001-12-03 02:05:55', 'Vivamus tortor.', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 480);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 1, 9, 70, '2005-01-29 02:44:24', 'Nulla tellus.', 'Etiam faucibus cursus urna. Ut tellus.', 544);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 1, 3, 50, '2011-01-07 20:40:20', 'Nulla nisl.', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 864);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 1, 3, 20, '2016-10-30 07:56:14', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 744);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 2, 5, 28, '2017-04-23 12:25:40', 'Integer tincidunt ante vel ipsum.', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 254);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 1, 9, 3, '2000-09-05 07:28:29', 'Morbi ut odio.', 'Suspendisse accumsan tortor quis turpis. Sed ante.', 93);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 3, 2, 66, '2001-01-28 02:45:50', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', 801);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 1, 3, 16, '2005-05-20 09:48:38', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Maecenas tincidunt lacus at velit.', 376);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 1, 5, 4, '2012-12-20 00:23:20', 'Proin eu mi.', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 820);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 2, 6, 16, '2002-04-14 10:43:58', 'Pellentesque viverra pede ac diam.', 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', 240);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 3, 6, 24, '2006-08-23 12:06:32', 'Donec ut mauris eget massa tempor convallis.', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', 224);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 3, 6, 77, '2009-06-25 09:49:01', 'In hac habitasse platea dictumst.', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 590);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 2, 2, 14, '2000-03-09 04:24:11', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 770);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 1, 6, 13, '2014-10-24 08:39:44', 'Phasellus sit amet erat.', 'Aliquam erat volutpat. In congue.', 737);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 1, 5, 7, '2010-02-08 16:01:06', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', 448);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 2, 8, 36, '2002-04-27 13:01:43', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 569);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 1, 10, 10, '2004-04-15 19:45:14', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 308);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 3, 1, 30, '2017-05-21 04:45:34', 'Nulla ac enim.', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 509);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 1, 10, 69, '2015-08-22 18:34:13', 'Aenean lectus.', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.', 426);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 3, 3, 59, '2000-06-02 06:00:43', 'Aenean lectus.', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 408);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 3, 7, 24, '2009-12-05 17:30:50', 'Duis mattis egestas metus.', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', 900);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 2, 10, 63, '2001-04-28 09:27:16', 'Sed sagittis.', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 589);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 3, 6, 42, '2011-06-12 20:27:35', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 708);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 1, 6, 15, '2012-09-11 04:57:56', 'Proin eu mi.', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 28);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 2, 4, 24, '2006-04-26 21:41:48', 'Maecenas tincidunt lacus at velit.', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', 313);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 1, 5, 23, '2009-07-04 22:57:45', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 709);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 2, 7, 36, '2013-11-19 19:40:17', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', 354);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 3, 8, 52, '2016-04-03 04:45:17', 'Nulla tempus.', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', 730);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 2, 1, 65, '2016-06-12 04:17:08', 'Duis consequat dui nec nisi volutpat eleifend.', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 754);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 3, 9, 8, '2017-02-26 07:11:40', 'Integer non velit.', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 429);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (0, 2, 3, 10, '2016-02-09 04:29:41', 'Aliquam non mauris.', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 46);
insert into posts (is_active, moderation_status, moderator_id, user_id, time, title, text, view_count) values (1, 1, 9, 66, '2006-03-08 11:21:56', 'Duis ac nibh.', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 311);

insert into post_votes (user_id, post_id, time, value) values (65, 16, '2015-02-20 22:29:34', 1);
insert into post_votes (user_id, post_id, time, value) values (53, 73, '2002-09-01 02:30:05', 1);
insert into post_votes (user_id, post_id, time, value) values (73, 34, '2010-11-28 08:09:00', -1);
insert into post_votes (user_id, post_id, time, value) values (46, 34, '2002-09-29 18:18:24', 1);
insert into post_votes (user_id, post_id, time, value) values (59, 1, '2016-12-27 22:37:05', -1);
insert into post_votes (user_id, post_id, time, value) values (73, 43, '2017-10-21 09:35:36', 1);
insert into post_votes (user_id, post_id, time, value) values (75, 47, '2013-02-10 06:23:01', 1);
insert into post_votes (user_id, post_id, time, value) values (41, 52, '2000-09-11 10:11:36', 1);
insert into post_votes (user_id, post_id, time, value) values (7, 43, '2008-12-07 15:07:58', -1);
insert into post_votes (user_id, post_id, time, value) values (58, 2, '2015-07-01 01:44:02', -1);
insert into post_votes (user_id, post_id, time, value) values (52, 17, '2016-12-26 16:41:34', -1);
insert into post_votes (user_id, post_id, time, value) values (39, 12, '2014-07-20 08:25:03', 1);
insert into post_votes (user_id, post_id, time, value) values (50, 56, '2019-08-17 18:46:39', -1);
insert into post_votes (user_id, post_id, time, value) values (34, 3, '2014-06-09 08:37:21', 1);
insert into post_votes (user_id, post_id, time, value) values (25, 68, '2016-03-13 02:13:00', -1);
insert into post_votes (user_id, post_id, time, value) values (52, 55, '2009-10-17 00:44:52', 1);
insert into post_votes (user_id, post_id, time, value) values (22, 11, '2019-04-20 14:10:22', -1);
insert into post_votes (user_id, post_id, time, value) values (3, 49, '2001-02-13 19:15:38', 1);
insert into post_votes (user_id, post_id, time, value) values (21, 35, '2000-07-22 01:54:34', -1);
insert into post_votes (user_id, post_id, time, value) values (60, 23, '2006-10-09 12:51:56', -1);
insert into post_votes (user_id, post_id, time, value) values (49, 61, '2011-06-13 22:50:06', -1);
insert into post_votes (user_id, post_id, time, value) values (7, 65, '2019-09-30 21:26:14', -1);
insert into post_votes (user_id, post_id, time, value) values (35, 20, '2008-02-06 21:50:07', -1);
insert into post_votes (user_id, post_id, time, value) values (51, 34, '2019-03-21 00:09:32', 1);
insert into post_votes (user_id, post_id, time, value) values (42, 39, '2018-09-01 10:24:19', 1);
insert into post_votes (user_id, post_id, time, value) values (27, 42, '2014-12-18 19:33:15', -1);
insert into post_votes (user_id, post_id, time, value) values (68, 13, '2007-08-18 19:33:59', -1);
insert into post_votes (user_id, post_id, time, value) values (23, 58, '2016-11-14 22:06:39', 1);
insert into post_votes (user_id, post_id, time, value) values (6, 7, '2005-08-13 10:02:17', 1);
insert into post_votes (user_id, post_id, time, value) values (38, 19, '2007-11-06 07:20:14', 1);
insert into post_votes (user_id, post_id, time, value) values (76, 42, '2000-10-19 19:54:01', 1);
insert into post_votes (user_id, post_id, time, value) values (48, 8, '2003-01-17 14:14:32', -1);
insert into post_votes (user_id, post_id, time, value) values (56, 48, '2001-08-25 07:57:41', 1);
insert into post_votes (user_id, post_id, time, value) values (16, 43, '2017-08-25 16:56:08', 1);
insert into post_votes (user_id, post_id, time, value) values (66, 15, '2009-10-31 08:08:32', 1);
insert into post_votes (user_id, post_id, time, value) values (54, 63, '2002-06-28 23:14:16', 1);
insert into post_votes (user_id, post_id, time, value) values (68, 10, '2010-06-01 18:18:47', 1);
insert into post_votes (user_id, post_id, time, value) values (60, 72, '2018-12-10 07:35:21', 1);
insert into post_votes (user_id, post_id, time, value) values (68, 7, '2019-03-08 15:34:14', 1);
insert into post_votes (user_id, post_id, time, value) values (76, 18, '2019-08-23 20:18:47', 1);
insert into post_votes (user_id, post_id, time, value) values (63, 70, '2013-08-13 19:27:43', -1);
insert into post_votes (user_id, post_id, time, value) values (10, 50, '2009-10-15 17:35:36', 1);
insert into post_votes (user_id, post_id, time, value) values (27, 69, '2016-07-25 23:12:40', 1);
insert into post_votes (user_id, post_id, time, value) values (56, 49, '2013-04-09 19:30:05', -1);
insert into post_votes (user_id, post_id, time, value) values (50, 44, '2018-03-14 04:31:26', 1);
insert into post_votes (user_id, post_id, time, value) values (57, 49, '2018-10-16 23:18:24', 1);
insert into post_votes (user_id, post_id, time, value) values (61, 23, '2014-05-25 01:02:31', -1);
insert into post_votes (user_id, post_id, time, value) values (21, 22, '2018-06-05 03:13:24', 1);
insert into post_votes (user_id, post_id, time, value) values (44, 52, '2015-08-10 14:20:26', 1);
insert into post_votes (user_id, post_id, time, value) values (43, 75, '2015-03-12 21:55:52', 1);
insert into post_votes (user_id, post_id, time, value) values (42, 35, '2005-10-21 22:59:53', -1);
insert into post_votes (user_id, post_id, time, value) values (59, 51, '2018-08-29 07:27:43', -1);
insert into post_votes (user_id, post_id, time, value) values (68, 75, '2009-12-31 04:37:22', -1);
insert into post_votes (user_id, post_id, time, value) values (59, 55, '2016-07-19 18:19:05', 1);
insert into post_votes (user_id, post_id, time, value) values (34, 18, '2019-01-19 08:12:34', -1);
insert into post_votes (user_id, post_id, time, value) values (8, 64, '2012-01-28 04:30:14', 1);
insert into post_votes (user_id, post_id, time, value) values (72, 52, '2006-06-03 03:52:33', 1);
insert into post_votes (user_id, post_id, time, value) values (29, 59, '2017-02-22 19:01:40', 1);
insert into post_votes (user_id, post_id, time, value) values (54, 68, '2017-04-21 19:11:21', -1);
insert into post_votes (user_id, post_id, time, value) values (8, 17, '2011-03-10 13:36:16', 1);
insert into post_votes (user_id, post_id, time, value) values (4, 25, '2018-11-24 04:15:35', 1);
insert into post_votes (user_id, post_id, time, value) values (6, 76, '2010-06-15 23:06:05', -1);
insert into post_votes (user_id, post_id, time, value) values (24, 60, '2001-11-26 12:33:37', -1);
insert into post_votes (user_id, post_id, time, value) values (28, 44, '2004-11-20 21:01:45', -1);
insert into post_votes (user_id, post_id, time, value) values (75, 61, '2002-08-12 20:36:44', 1);
insert into post_votes (user_id, post_id, time, value) values (58, 13, '2019-04-16 14:29:23', -1);
insert into post_votes (user_id, post_id, time, value) values (64, 55, '2016-06-19 22:04:53', -1);
insert into post_votes (user_id, post_id, time, value) values (45, 72, '2018-04-01 21:43:52', -1);
insert into post_votes (user_id, post_id, time, value) values (25, 2, '2014-07-11 21:19:13', 1);
insert into post_votes (user_id, post_id, time, value) values (4, 53, '2009-11-23 08:52:38', 1);
insert into post_votes (user_id, post_id, time, value) values (22, 75, '2008-11-10 10:42:31', -1);
insert into post_votes (user_id, post_id, time, value) values (63, 42, '2006-02-18 09:36:00', 1);
insert into post_votes (user_id, post_id, time, value) values (19, 53, '2002-01-06 21:16:59', 1);
insert into post_votes (user_id, post_id, time, value) values (44, 36, '2016-02-18 18:15:35', 1);
insert into post_votes (user_id, post_id, time, value) values (32, 24, '2011-11-17 13:32:42', 1);
insert into post_votes (user_id, post_id, time, value) values (10, 75, '2008-10-03 15:10:32', 1);
insert into post_votes (user_id, post_id, time, value) values (19, 16, '2018-03-13 15:11:06', -1);
insert into post_votes (user_id, post_id, time, value) values (55, 73, '2003-03-13 08:16:22', 1);
insert into post_votes (user_id, post_id, time, value) values (49, 1, '2013-04-01 20:07:02', 1);
insert into post_votes (user_id, post_id, time, value) values (36, 29, '2008-04-22 18:52:06', -1);
insert into post_votes (user_id, post_id, time, value) values (45, 57, '2017-04-23 13:03:50', -1);
insert into post_votes (user_id, post_id, time, value) values (29, 6, '2018-06-21 19:07:53', -1);
insert into post_votes (user_id, post_id, time, value) values (39, 73, '2017-04-06 19:04:22', -1);
insert into post_votes (user_id, post_id, time, value) values (26, 5, '2013-09-22 02:37:17', -1);
insert into post_votes (user_id, post_id, time, value) values (25, 45, '2003-06-11 08:33:12', -1);
insert into post_votes (user_id, post_id, time, value) values (28, 55, '2002-10-18 19:55:21', 1);
insert into post_votes (user_id, post_id, time, value) values (68, 76, '2015-08-08 06:48:33', -1);
insert into post_votes (user_id, post_id, time, value) values (34, 70, '2005-12-08 06:57:40', -1);
insert into post_votes (user_id, post_id, time, value) values (22, 65, '2019-07-28 09:26:08', -1);
insert into post_votes (user_id, post_id, time, value) values (3, 25, '2011-11-19 20:23:18', -1);
insert into post_votes (user_id, post_id, time, value) values (24, 45, '2004-10-17 03:55:21', 1);
insert into post_votes (user_id, post_id, time, value) values (31, 39, '2019-01-31 14:28:17', 1);
insert into post_votes (user_id, post_id, time, value) values (76, 51, '2005-12-05 14:45:25', -1);
insert into post_votes (user_id, post_id, time, value) values (7, 34, '2001-12-11 15:11:52', 1);
insert into post_votes (user_id, post_id, time, value) values (3, 52, '2000-12-26 16:30:28', -1);
insert into post_votes (user_id, post_id, time, value) values (30, 35, '2010-12-25 05:40:06', -1);
insert into post_votes (user_id, post_id, time, value) values (47, 13, '2003-07-27 23:23:32', 1);
insert into post_votes (user_id, post_id, time, value) values (10, 7, '2017-09-30 16:57:49', 1);
insert into post_votes (user_id, post_id, time, value) values (68, 57, '2013-10-02 09:20:48', 1);
insert into post_votes (user_id, post_id, time, value) values (24, 37, '2008-08-28 11:21:04', -1);
insert into post_votes (user_id, post_id, time, value) values (6, 5, '2011-09-29 23:40:00', 1);
insert into post_votes (user_id, post_id, time, value) values (66, 50, '2003-02-27 17:38:29', -1);
insert into post_votes (user_id, post_id, time, value) values (60, 77, '2018-10-26 06:22:04', 1);
insert into post_votes (user_id, post_id, time, value) values (8, 63, '2012-01-18 23:18:11', -1);
insert into post_votes (user_id, post_id, time, value) values (73, 62, '2001-03-28 21:47:07', 1);
insert into post_votes (user_id, post_id, time, value) values (42, 60, '2015-09-29 23:15:32', -1);
insert into post_votes (user_id, post_id, time, value) values (71, 2, '2019-01-09 08:06:05', -1);
insert into post_votes (user_id, post_id, time, value) values (41, 4, '2009-02-16 21:21:40', 1);
insert into post_votes (user_id, post_id, time, value) values (20, 14, '2005-06-21 11:41:02', 1);
insert into post_votes (user_id, post_id, time, value) values (76, 54, '2000-11-25 09:15:18', -1);
insert into post_votes (user_id, post_id, time, value) values (5, 44, '2016-01-14 22:01:44', 1);
insert into post_votes (user_id, post_id, time, value) values (22, 13, '2006-03-23 10:18:10', -1);
insert into post_votes (user_id, post_id, time, value) values (54, 11, '2014-09-02 13:27:05', 1);
insert into post_votes (user_id, post_id, time, value) values (26, 67, '2002-06-15 03:52:31', -1);
insert into post_votes (user_id, post_id, time, value) values (54, 42, '2006-07-26 13:06:26', 1);
insert into post_votes (user_id, post_id, time, value) values (65, 29, '2005-11-28 12:58:39', 1);
insert into post_votes (user_id, post_id, time, value) values (21, 5, '2004-12-30 03:44:46', 1);
insert into post_votes (user_id, post_id, time, value) values (68, 57, '2010-05-30 20:59:24', -1);
insert into post_votes (user_id, post_id, time, value) values (70, 48, '2005-06-13 00:32:04', -1);
insert into post_votes (user_id, post_id, time, value) values (17, 41, '2000-08-26 02:17:43', -1);
insert into post_votes (user_id, post_id, time, value) values (8, 51, '2012-12-17 04:41:24', -1);
insert into post_votes (user_id, post_id, time, value) values (19, 5, '2016-05-01 08:04:45', 1);
insert into post_votes (user_id, post_id, time, value) values (54, 54, '2001-06-30 18:23:20', 1);
insert into post_votes (user_id, post_id, time, value) values (18, 49, '2012-11-30 00:18:01', -1);
insert into post_votes (user_id, post_id, time, value) values (27, 21, '2009-06-28 08:32:45', -1);
insert into post_votes (user_id, post_id, time, value) values (32, 14, '2010-11-23 00:37:27', -1);
insert into post_votes (user_id, post_id, time, value) values (4, 37, '2003-12-26 20:58:56', 1);
insert into post_votes (user_id, post_id, time, value) values (49, 11, '2005-02-27 18:52:27', 1);
insert into post_votes (user_id, post_id, time, value) values (3, 10, '2000-07-13 08:41:58', -1);
insert into post_votes (user_id, post_id, time, value) values (44, 26, '2010-03-04 06:40:28', -1);
insert into post_votes (user_id, post_id, time, value) values (21, 40, '2005-05-17 21:00:51', -1);
insert into post_votes (user_id, post_id, time, value) values (5, 74, '2014-07-22 22:40:54', -1);
insert into post_votes (user_id, post_id, time, value) values (19, 64, '2017-07-29 23:33:39', -1);
insert into post_votes (user_id, post_id, time, value) values (12, 65, '2013-08-20 22:01:04', 1);
insert into post_votes (user_id, post_id, time, value) values (17, 76, '2009-05-07 16:53:22', -1);
insert into post_votes (user_id, post_id, time, value) values (11, 59, '2013-10-19 17:14:19', 1);
insert into post_votes (user_id, post_id, time, value) values (27, 48, '2002-07-09 00:34:12', 1);
insert into post_votes (user_id, post_id, time, value) values (37, 58, '2009-07-07 01:33:55', -1);
insert into post_votes (user_id, post_id, time, value) values (21, 54, '2017-03-14 09:59:51', -1);
insert into post_votes (user_id, post_id, time, value) values (25, 39, '2005-05-04 12:24:04', -1);
insert into post_votes (user_id, post_id, time, value) values (54, 76, '2003-09-05 09:07:55', -1);
insert into post_votes (user_id, post_id, time, value) values (34, 65, '2013-04-23 15:48:19', -1);
insert into post_votes (user_id, post_id, time, value) values (69, 40, '2008-11-30 15:45:07', -1);
insert into post_votes (user_id, post_id, time, value) values (18, 43, '2015-07-25 22:06:37', -1);
insert into post_votes (user_id, post_id, time, value) values (60, 46, '2015-07-13 19:48:34', -1);
insert into post_votes (user_id, post_id, time, value) values (32, 32, '2000-07-14 15:39:03', -1);
insert into post_votes (user_id, post_id, time, value) values (62, 35, '2006-01-20 16:28:22', -1);
insert into post_votes (user_id, post_id, time, value) values (30, 40, '2019-08-28 19:42:03', -1);
insert into post_votes (user_id, post_id, time, value) values (9, 41, '2003-04-16 09:26:07', 1);
insert into post_votes (user_id, post_id, time, value) values (37, 68, '2002-10-13 04:45:15', -1);

insert into tags (name) values ('ZINC OXIDE, OCTINOXATE, OCTISALATE');
insert into tags (name) values ('Aluminum Chlorohydrate');
insert into tags (name) values ('CALCIUM ASCORBATE, CALCIUM THREONATE, CHOLECALCIFEROL, ALPHA-TOCOPHEROL ACETATE, FOLIC ACID, PYRIDOXINE HYDROCHLORIDE, CALCIUM, IRON, FERROUS ASPARTO GLYCINATE, DOCONEXENT, ICOSAPENT, and LINOLENIC AC');
insert into tags (name) values ('Methocarbamol');
insert into tags (name) values ('Risperidone');
insert into tags (name) values ('Losartan Potassium');
insert into tags (name) values ('valacyclovir hydrochloride');
insert into tags (name) values ('VASOPRESSIN');
insert into tags (name) values ('Pyridostigmine Bromide');
insert into tags (name) values ('Sodium chloride');
insert into tags (name) values ('Benazepril Hydrochloride');
insert into tags (name) values ('Acetaminophen');
insert into tags (name) values ('Fenofibrate');
insert into tags (name) values ('telavancin hydrochloride');
insert into tags (name) values ('oxycodone hydrochloride');

insert into tag2post (post_id, tag_id) values (2, 10);
insert into tag2post (post_id, tag_id) values (19, 9);
insert into tag2post (post_id, tag_id) values (6, 3);
insert into tag2post (post_id, tag_id) values (21, 4);
insert into tag2post (post_id, tag_id) values (39, 14);
insert into tag2post (post_id, tag_id) values (6, 6);
insert into tag2post (post_id, tag_id) values (39, 3);
insert into tag2post (post_id, tag_id) values (77, 2);
insert into tag2post (post_id, tag_id) values (42, 7);
insert into tag2post (post_id, tag_id) values (16, 1);
insert into tag2post (post_id, tag_id) values (46, 6);
insert into tag2post (post_id, tag_id) values (50, 4);
insert into tag2post (post_id, tag_id) values (20, 8);
insert into tag2post (post_id, tag_id) values (47, 2);
insert into tag2post (post_id, tag_id) values (61, 3);
insert into tag2post (post_id, tag_id) values (26, 3);
insert into tag2post (post_id, tag_id) values (30, 5);
insert into tag2post (post_id, tag_id) values (67, 8);
insert into tag2post (post_id, tag_id) values (63, 6);
insert into tag2post (post_id, tag_id) values (64, 4);
insert into tag2post (post_id, tag_id) values (14, 12);
insert into tag2post (post_id, tag_id) values (33, 8);
insert into tag2post (post_id, tag_id) values (68, 11);
insert into tag2post (post_id, tag_id) values (65, 3);
insert into tag2post (post_id, tag_id) values (56, 12);
insert into tag2post (post_id, tag_id) values (51, 15);
insert into tag2post (post_id, tag_id) values (64, 15);
insert into tag2post (post_id, tag_id) values (24, 1);
insert into tag2post (post_id, tag_id) values (31, 11);
insert into tag2post (post_id, tag_id) values (1, 15);
insert into tag2post (post_id, tag_id) values (69, 2);
insert into tag2post (post_id, tag_id) values (9, 4);
insert into tag2post (post_id, tag_id) values (37, 11);
insert into tag2post (post_id, tag_id) values (31, 11);
insert into tag2post (post_id, tag_id) values (51, 14);
insert into tag2post (post_id, tag_id) values (56, 12);
insert into tag2post (post_id, tag_id) values (20, 9);
insert into tag2post (post_id, tag_id) values (34, 15);
insert into tag2post (post_id, tag_id) values (47, 3);
insert into tag2post (post_id, tag_id) values (54, 5);
insert into tag2post (post_id, tag_id) values (55, 11);
insert into tag2post (post_id, tag_id) values (61, 15);
insert into tag2post (post_id, tag_id) values (62, 6);
insert into tag2post (post_id, tag_id) values (41, 1);
insert into tag2post (post_id, tag_id) values (60, 7);
insert into tag2post (post_id, tag_id) values (69, 2);
insert into tag2post (post_id, tag_id) values (52, 5);
insert into tag2post (post_id, tag_id) values (69, 11);
insert into tag2post (post_id, tag_id) values (53, 12);
insert into tag2post (post_id, tag_id) values (51, 3);
insert into tag2post (post_id, tag_id) values (48, 14);
insert into tag2post (post_id, tag_id) values (6, 11);
insert into tag2post (post_id, tag_id) values (38, 14);
insert into tag2post (post_id, tag_id) values (1, 7);
insert into tag2post (post_id, tag_id) values (15, 10);
insert into tag2post (post_id, tag_id) values (5, 2);
insert into tag2post (post_id, tag_id) values (68, 14);
insert into tag2post (post_id, tag_id) values (6, 3);
insert into tag2post (post_id, tag_id) values (21, 15);
insert into tag2post (post_id, tag_id) values (31, 1);
insert into tag2post (post_id, tag_id) values (34, 8);
insert into tag2post (post_id, tag_id) values (25, 6);
insert into tag2post (post_id, tag_id) values (28, 4);
insert into tag2post (post_id, tag_id) values (43, 5);
insert into tag2post (post_id, tag_id) values (2, 14);
insert into tag2post (post_id, tag_id) values (66, 4);
insert into tag2post (post_id, tag_id) values (34, 9);
insert into tag2post (post_id, tag_id) values (28, 3);
insert into tag2post (post_id, tag_id) values (28, 12);
insert into tag2post (post_id, tag_id) values (75, 14);
insert into tag2post (post_id, tag_id) values (62, 3);
insert into tag2post (post_id, tag_id) values (33, 15);
insert into tag2post (post_id, tag_id) values (47, 11);
insert into tag2post (post_id, tag_id) values (75, 11);
insert into tag2post (post_id, tag_id) values (51, 6);
insert into tag2post (post_id, tag_id) values (17, 12);
insert into tag2post (post_id, tag_id) values (52, 10);
insert into tag2post (post_id, tag_id) values (64, 9);
insert into tag2post (post_id, tag_id) values (23, 12);
insert into tag2post (post_id, tag_id) values (61, 2);
insert into tag2post (post_id, tag_id) values (48, 8);
insert into tag2post (post_id, tag_id) values (71, 6);
insert into tag2post (post_id, tag_id) values (72, 9);
insert into tag2post (post_id, tag_id) values (71, 14);
insert into tag2post (post_id, tag_id) values (26, 13);
insert into tag2post (post_id, tag_id) values (5, 11);
insert into tag2post (post_id, tag_id) values (66, 2);
insert into tag2post (post_id, tag_id) values (17, 8);
insert into tag2post (post_id, tag_id) values (13, 12);
insert into tag2post (post_id, tag_id) values (59, 9);
insert into tag2post (post_id, tag_id) values (64, 13);
insert into tag2post (post_id, tag_id) values (76, 15);
insert into tag2post (post_id, tag_id) values (46, 14);
insert into tag2post (post_id, tag_id) values (15, 13);
insert into tag2post (post_id, tag_id) values (63, 5);
insert into tag2post (post_id, tag_id) values (60, 14);
insert into tag2post (post_id, tag_id) values (60, 8);
insert into tag2post (post_id, tag_id) values (3, 3);
insert into tag2post (post_id, tag_id) values (32, 1);
insert into tag2post (post_id, tag_id) values (71, 15);
insert into tag2post (post_id, tag_id) values (64, 12);
insert into tag2post (post_id, tag_id) values (22, 3);
insert into tag2post (post_id, tag_id) values (17, 9);
insert into tag2post (post_id, tag_id) values (24, 2);
insert into tag2post (post_id, tag_id) values (15, 6);
insert into tag2post (post_id, tag_id) values (18, 3);
insert into tag2post (post_id, tag_id) values (10, 8);
insert into tag2post (post_id, tag_id) values (54, 2);
insert into tag2post (post_id, tag_id) values (35, 13);
insert into tag2post (post_id, tag_id) values (63, 10);
insert into tag2post (post_id, tag_id) values (6, 5);
insert into tag2post (post_id, tag_id) values (22, 8);
insert into tag2post (post_id, tag_id) values (39, 2);
insert into tag2post (post_id, tag_id) values (67, 11);
insert into tag2post (post_id, tag_id) values (6, 1);
insert into tag2post (post_id, tag_id) values (71, 14);
insert into tag2post (post_id, tag_id) values (19, 11);
insert into tag2post (post_id, tag_id) values (2, 1);
insert into tag2post (post_id, tag_id) values (10, 5);
insert into tag2post (post_id, tag_id) values (33, 14);

insert into post_comments (parent_id, post_id, user_id, time, text) values (35, 58, 22, '2000-07-03 09:23:32', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (82, 62, 40, '2010-02-23 22:12:31', 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (20, 37, 34, '2011-07-15 14:10:55', 'In congue. Etiam justo.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (22, 72, 74, '2010-12-22 09:47:02', 'Morbi non lectus.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (56, 10, 77, '2002-05-06 14:06:41', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (95, 30, 36, '2009-02-02 12:36:35', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (34, 39, 44, '2010-09-21 09:33:54', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (89, 71, 56, '2003-06-10 07:44:06', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (96, 74, 33, '2002-06-13 11:16:04', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (85, 21, 23, '2007-04-16 12:23:16', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (51, 25, 48, '2007-03-07 16:00:12', 'Phasellus in felis. Donec semper sapien a libero.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (45, 35, 10, '2013-03-26 16:25:25', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (94, 27, 2, '2018-01-12 19:22:40', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (9, 27, 17, '2001-09-26 21:49:29', 'Nam nulla.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (8, 6, 27, '2002-05-17 23:13:17', 'Integer ac neque.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (52, 29, 63, '2018-12-12 04:20:51', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (88, 28, 46, '2007-11-16 02:06:50', 'Ut tellus.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (87, 71, 21, '2013-01-18 02:26:50', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (61, 75, 27, '2004-01-06 06:52:55', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (29, 45, 41, '2003-02-19 07:06:25', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (33, 14, 76, '2019-06-27 15:37:18', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (42, 9, 69, '2009-12-19 10:57:03', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (22, 23, 21, '2007-08-21 21:18:08', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (75, 52, 33, '2013-07-06 14:46:37', 'In quis justo.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (56, 18, 24, '2004-10-20 04:56:19', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (8, 8, 6, '2012-03-26 10:01:47', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (16, 8, 46, '2014-09-24 10:26:59', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (48, 46, 3, '2010-11-22 03:18:12', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (35, 22, 1, '2000-07-13 15:00:53', 'In eleifend quam a odio.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (60, 67, 35, '2014-03-05 11:15:40', 'In congue. Etiam justo.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (47, 3, 58, '2016-11-29 07:18:22', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (6, 13, 3, '2005-07-26 23:18:09', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (80, 67, 47, '2018-04-14 12:40:40', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (54, 69, 75, '2013-09-08 05:39:41', 'Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (68, 12, 66, '2000-07-18 00:33:19', 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (99, 20, 72, '2019-10-19 05:13:21', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (0, 35, 28, '2011-07-15 03:22:23', 'Quisque ut erat.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (90, 67, 22, '2002-06-03 07:31:27', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (11, 61, 11, '2012-01-30 19:18:56', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (25, 24, 44, '2010-02-23 01:36:29', 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (58, 18, 71, '2008-04-11 10:50:08', 'Fusce consequat.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (63, 6, 51, '2011-12-30 18:01:59', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (38, 33, 74, '2001-01-08 20:20:54', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (82, 40, 67, '2001-03-11 20:32:37', 'Proin at turpis a pede posuere nonummy.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (38, 59, 5, '2010-05-05 09:38:52', 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (82, 67, 77, '2008-11-27 17:03:17', 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (94, 20, 74, '2000-12-02 06:19:52', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (87, 21, 46, '2009-06-16 19:25:40', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (95, 29, 39, '2009-12-15 00:53:04', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (54, 31, 35, '2004-12-18 01:35:19', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (52, 63, 35, '2017-06-01 21:34:48', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (22, 61, 58, '2004-10-15 02:00:15', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (1, 30, 25, '2001-07-04 05:28:15', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (47, 64, 67, '2013-10-15 08:28:06', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (28, 6, 36, '2010-11-16 06:42:00', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (74, 49, 7, '2008-11-19 11:18:53', 'Ut at dolor quis odio consequat varius.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (77, 50, 9, '2007-02-25 18:52:20', 'Pellentesque viverra pede ac diam.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (51, 5, 10, '2018-06-22 09:54:19', 'Praesent blandit. Nam nulla.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (51, 30, 26, '2014-09-20 01:35:30', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (32, 66, 3, '2002-09-10 19:20:13', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (44, 65, 25, '2013-01-17 00:40:22', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (89, 26, 19, '2015-04-11 16:36:02', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (35, 22, 68, '2007-07-18 07:59:38', 'Nunc rhoncus dui vel sem. Sed sagittis.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (40, 52, 8, '2019-07-22 09:18:08', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (93, 55, 48, '2011-10-01 11:19:37', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (33, 40, 73, '2018-08-18 06:41:27', 'In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (0, 59, 43, '2009-09-06 10:53:34', 'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (49, 40, 9, '2008-12-06 19:02:21', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (81, 34, 46, '2015-08-10 16:26:01', 'Curabitur convallis.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (14, 51, 35, '2018-11-03 09:33:47', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (37, 15, 46, '2018-08-26 10:25:29', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (73, 64, 45, '2018-04-21 15:31:58', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (0, 19, 36, '2018-06-12 06:55:20', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (24, 50, 22, '2008-04-16 07:44:57', 'Praesent lectus.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (35, 71, 19, '2001-06-13 02:38:28', 'In quis justo.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (16, 48, 14, '2013-12-21 15:07:36', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (45, 71, 33, '2010-04-06 00:21:48', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (95, 68, 54, '2019-12-22 20:23:35', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (60, 37, 69, '2003-10-21 05:26:47', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (16, 37, 71, '2001-01-10 20:52:33', 'In hac habitasse platea dictumst.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (54, 9, 69, '2015-11-21 03:03:25', 'Praesent blandit.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (49, 74, 35, '2002-07-26 01:02:36', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (0, 50, 18, '2013-01-14 05:44:05', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (29, 39, 27, '2006-02-10 10:42:43', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (6, 18, 15, '2019-07-31 19:33:54', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (42, 2, 69, '2017-07-29 04:45:02', 'Nulla ac enim.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (91, 49, 34, '2012-04-30 06:52:15', 'Aliquam erat volutpat. In congue. Etiam justo.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (38, 77, 27, '2019-06-12 18:55:11', 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (13, 45, 18, '2000-11-30 21:24:47', 'Suspendisse accumsan tortor quis turpis. Sed ante.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (6, 67, 38, '2009-04-29 07:47:23', 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (55, 30, 71, '2003-03-26 01:55:38', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (83, 51, 23, '2017-03-14 00:03:14', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (98, 36, 53, '2001-11-09 22:41:43', 'In hac habitasse platea dictumst.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (57, 18, 73, '2007-08-05 07:08:28', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (98, 49, 76, '2004-03-27 08:06:14', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (79, 69, 4, '2009-08-08 06:02:39', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (13, 49, 30, '2013-03-14 01:02:32', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (0, 21, 65, '2006-04-06 06:33:55', 'Morbi ut odio.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (1, 38, 54, '2011-12-29 12:41:40', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.');
insert into post_comments (parent_id, post_id, user_id, time, text) values (70, 47, 40, '2003-02-18 10:39:10', 'Quisque id justo sit amet sapien dignissim vestibulum.');

